// Generated by gencpp from file calypso/mapMessage.msg
// DO NOT EDIT!


#ifndef CALYPSO_MESSAGE_MAPMESSAGE_H
#define CALYPSO_MESSAGE_MAPMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calypso
{
template <class ContainerAllocator>
struct mapMessage_
{
  typedef mapMessage_<ContainerAllocator> Type;

  mapMessage_()
    : x(0)
    , y(0)
    , aboveGround(0)  {
    }
  mapMessage_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , aboveGround(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _aboveGround_type;
  _aboveGround_type aboveGround;





  typedef boost::shared_ptr< ::calypso::mapMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calypso::mapMessage_<ContainerAllocator> const> ConstPtr;

}; // struct mapMessage_

typedef ::calypso::mapMessage_<std::allocator<void> > mapMessage;

typedef boost::shared_ptr< ::calypso::mapMessage > mapMessagePtr;
typedef boost::shared_ptr< ::calypso::mapMessage const> mapMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calypso::mapMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calypso::mapMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::calypso::mapMessage_<ContainerAllocator1> & lhs, const ::calypso::mapMessage_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.aboveGround == rhs.aboveGround;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::calypso::mapMessage_<ContainerAllocator1> & lhs, const ::calypso::mapMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace calypso

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::calypso::mapMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calypso::mapMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calypso::mapMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calypso::mapMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calypso::mapMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calypso::mapMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calypso::mapMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22ea157c52d768522b54b46b2168b9b4";
  }

  static const char* value(const ::calypso::mapMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22ea157c52d76852ULL;
  static const uint64_t static_value2 = 0x2b54b46b2168b9b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::calypso::mapMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calypso/mapMessage";
  }

  static const char* value(const ::calypso::mapMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calypso::mapMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 aboveGround\n"
;
  }

  static const char* value(const ::calypso::mapMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calypso::mapMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.aboveGround);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mapMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calypso::mapMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calypso::mapMessage_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "aboveGround: ";
    Printer<int32_t>::stream(s, indent + "  ", v.aboveGround);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALYPSO_MESSAGE_MAPMESSAGE_H
